#!/usr/bin/env python3
"""Generate an ASCII-only JS snippet that reports the VIEWPORT coordinates of elements matching a
CSS selector (optionally filtered by visible text) -- the input for a TRUSTED click.

Why this exists: components that ignore synthetic el.click() (vaadin-grid rows, some React cards,
anything whose handler checks event.isTrusted) must be driven with
`CDP_CLICK="x,y"` -> Input.dispatchMouseEvent. Those coordinates have to come from
getBoundingClientRect() of the real element, and hand-writing that probe per element wastes a round.

Output per match:  #<n> x,y w=<w> h=<h> vis=<bool> tag=<tag> href=<href> text=<first 60 chars>
Feed the x,y of the match you want straight into CDP_CLICK.

  python3 mk_rect.py 'a[href*="water.crpt.ru"]' > js/r_water.js
  python3 mk_rect.py 'button' --text 'Найти'   > js/r_find.js
  python3 mk_rect.py '.grid-row' --nth 3       > js/r_row3.js   # only the 3rd match
  python3 mk_rect.py '.card' --scroll          > js/r_card.js   # scroll it into view FIRST

--scroll matters: Input.dispatchMouseEvent takes VIEWPORT coordinates, so an element sitting at
y=2049 in a 1105-tall viewport cannot be clicked at all until it is scrolled into view (vis=false
is the tell). scrollIntoView uses behavior:"instant" so the rect measured right after is the final
one.

Cyrillic in --text is emitted as \\uXXXX (survives scp + PowerShell ReadAllText), same rule as the
other mk_* generators.
"""
import sys


def esc(s: str) -> str:
    return "".join(c if 32 <= ord(c) < 127 and c not in '"\\' else "\\u%04x" % ord(c) for c in s)


def main() -> int:
    args = sys.argv[1:]
    if not args:
        print(__doc__, file=sys.stderr)
        return 2
    selector = args[0]
    text = ""
    nth = 0
    scroll = "--scroll" in args[1:]
    for i, a in enumerate(args[1:]):
        if a == "--text" and i + 2 <= len(args) - 1:
            text = args[i + 2]
        if a == "--nth" and i + 2 <= len(args) - 1:
            nth = int(args[i + 2])
    text_js = ""
    if text:
        text_js = f'''
  els = els.filter(e => (e.innerText || e.textContent || "").indexOf("{esc(text)}") >= 0);'''
    nth_js = f'''
  if ({nth} > 0) els = els.slice({nth} - 1, {nth});''' if nth else ""
    print(f'''/* generated by mk_rect.py: rects of {selector!r} (trusted-click coordinates) */
(() => {{
  let els = Array.prototype.slice.call(document.querySelectorAll("{esc(selector)}"));{text_js}{nth_js}
  if (!els.length) return "NO_MATCH selector={esc(selector)}";
  if ({int(scroll)}) {{ try {{ els[0].scrollIntoView({{block: "center", behavior: "instant"}}); }} catch (e) {{ els[0].scrollIntoView(); }} }}
  const out = ["MATCHES " + els.length + " viewport=" + innerWidth + "x" + innerHeight];
  els.slice(0, 40).forEach((e, i) => {{
    const r = e.getBoundingClientRect();
    const cx = Math.round(r.left + r.width / 2), cy = Math.round(r.top + r.height / 2);
    const vis = r.width > 0 && r.height > 0 && cy >= 0 && cy < innerHeight;
    const txt = (e.innerText || e.textContent || "").replace(/\\s+/g, " ").slice(0, 60);
    out.push("#" + (i + 1) + " " + cx + "," + cy + " w=" + Math.round(r.width) +
             " h=" + Math.round(r.height) + " vis=" + vis + " tag=" + e.tagName +
             " href=" + (e.getAttribute("href") || "-") + " text=" + txt);
  }});
  return out.join("\\n");
}})()''')
    return 0


if __name__ == "__main__":
    sys.exit(main())
