#!/usr/bin/env python3
"""Generate an ASCII-only JS snippet that picks an <option> in an ASP.NET dropdown and fires its
postback, for use as cdpq.sh's expression file.

Two field-proven constraints are baked in:
  * Cyrillic is emitted as \\uXXXX escapes -> the file survives scp/PowerShell ReadAllText intact.
  * The postback is DEFERRED via setTimeout -> Runtime.evaluate returns before the page reload
    tears down the JS context (otherwise CDP reports EVAL=NULL and you debug the wrong thing).

  python3 mk_setselect.py drdBrand "АТОЛ" > js/set_brand.js
  python3 mk_setselect.py drdModel "АТОЛ 25Ф" --contains > js/set_model.js
"""
import sys


def esc(s: str) -> str:
    return "".join(c if 32 <= ord(c) < 127 and c not in '"\\' else "\\u%04x" % ord(c) for c in s)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    suffix, want = sys.argv[1], sys.argv[2]
    contains = "--contains" in sys.argv[3:]
    test = "indexOf(want) >= 0" if contains else "indexOf(want) === 0"
    print(f'''/* generated by mk_setselect.py: {suffix} -> {want!r} (ASCII-only, deferred postback) */
(() => {{
  const sel = document.querySelector('select[id$="{suffix}"]');
  if (!sel) return "NO_SELECT {suffix}";
  const want = "{esc(want)}";
  let hit = null;
  for (const o of sel.options) {{ const t = (o.text || "").trim(); if (t.{test}) {{ hit = o; break; }} }}
  if (!hit) return "NO_OPTION " + Array.from(sel.options).map(o => o.text).join(" / ");
  sel.value = hit.value;
  const nm = sel.name;
  setTimeout(() => {{ try {{ __doPostBack(nm, ""); }} catch (e) {{ sel.dispatchEvent(new Event("change", {{bubbles:true}})); }} }}, 300);
  return "SCHEDULED " + nm + " => " + hit.text;
}})()''')
    return 0


if __name__ == "__main__":
    sys.exit(main())
