#!/usr/bin/env python3
"""Generate an ASCII-only JS snippet that resets the fs.atol.ru file-archive filter, types a phrase
into "Текст для поиска" and submits -- for use as cdpq.sh's expression file.

Same two constraints as mk_setselect.py: Cyrillic as \\uXXXX escapes (survives scp + PowerShell
ReadAllText), and the submit is DEFERRED via setTimeout so Runtime.evaluate returns before the
postback tears the JS context down.

  python3 mk_textsearch.py "прошивк" > js/s_fw.js
  python3 mk_textsearch.py "прошивк" --no-reset > js/s_fw.js   # keep current category/model
"""
import sys


def esc(s: str) -> str:
    return "".join(c if 32 <= ord(c) < 127 and c not in '"\\' else "\\u%04x" % ord(c) for c in s)


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    phrase = sys.argv[1]
    reset = "--no-reset" not in sys.argv[2:]
    reset_js = '''
  if (!window.__t67reset) {
    const rb = document.querySelector('input[id$="FileArchiveFilter_btnReset"]');
    if (rb) { window.__t67reset = 1; setTimeout(() => rb.click(), 200); return "RESET_SCHEDULED"; }
  }
  window.__t67reset = 0;''' if reset else ""
    print(f'''/* generated by mk_textsearch.py: search {phrase!r} (ASCII-only, deferred postback) */
(() => {{{reset_js}
  const tx = document.querySelector('input[id$="FileArchiveFilter_txtDescr"]');
  const btn = document.querySelector('input[id$="FileArchiveFilter_btnSearch"]');
  if (!tx || !btn) return "NO_CONTROLS";
  tx.value = "{esc(phrase)}";
  setTimeout(() => btn.click(), 300);
  return "SEARCH_SCHEDULED q=" + tx.value;
}})()''')
    return 0


if __name__ == "__main__":
    sys.exit(main())
