#!/usr/bin/env python3
"""Generate a JS snippet that lists the contents of a REMOTE .zip without downloading it:
HTTP Range-fetch the tail, parse the ZIP End-Of-Central-Directory, then Range-fetch just the
central directory and read every entry name.

A 1.2 GB archive costs a few hundred KB this way. Runs inside the page, so the site's anti-bot
cookie and session apply exactly as they do to a normal click.

  python3 mk_zipindex.py "/path/or/url/to.zip" [grep-substring] > js/zip_index.js
"""
import sys


def esc(s: str) -> str:
    return "".join(c if 32 <= ord(c) < 127 and c not in '"\\' else "\\u%04x" % ord(c) for c in s)


TEMPLATE = r'''/* generated by mk_zipindex.py: ZIP central-directory listing over HTTP Range */
(async () => {
  const url = "%(url)s";
  const filt = "%(filt)s";
  const out = [];
  const get = async (range) => {
    const r = await fetch(url, {credentials:"include", headers:{Range: range}});
    return {status:r.status, cr:r.headers.get("content-range"), buf: await r.arrayBuffer()};
  };
  let tail;
  try { tail = await get("bytes=-1048576"); } catch(e) { return "ERR fetch " + e; }
  out.push("TAIL status=" + tail.status + " content-range=" + tail.cr + " bytes=" + tail.buf.byteLength);
  if (tail.status !== 206) return out.join("\n") + "\nNO_RANGE_SUPPORT";
  const total = parseInt((tail.cr || "").split("/")[1] || "0", 10);
  const tv = new DataView(tail.buf);
  const tailStart = total - tail.buf.byteLength;
  let eocd = -1;
  for (let i = tail.buf.byteLength - 22; i >= 0; i--) {
    if (tv.getUint32(i, true) === 0x06054b50) { eocd = i; break; }
  }
  if (eocd < 0) return out.join("\n") + "\nNO_EOCD";
  let cdSize   = tv.getUint32(eocd + 12, true);
  let cdOffset = tv.getUint32(eocd + 16, true);
  let nEnt     = tv.getUint16(eocd + 10, true);
  out.push("EOCD entries=" + nEnt + " cdSize=" + cdSize + " cdOffset=" + cdOffset + " total=" + total);
  let cdBuf;
  if (cdOffset >= tailStart && cdOffset + cdSize <= total) {
    cdBuf = tail.buf.slice(cdOffset - tailStart, cdOffset - tailStart + cdSize);
  } else {
    const cd = await get("bytes=" + cdOffset + "-" + (cdOffset + cdSize - 1));
    if (cd.status !== 206) return out.join("\n") + "\nCD_FETCH_FAIL " + cd.status;
    cdBuf = cd.buf;
  }
  const dv = new DataView(cdBuf);
  const u8 = new Uint8Array(cdBuf);
  const utf8 = new TextDecoder("utf-8", {fatal:true});
  const cp866 = new TextDecoder("ibm866");
  const dec = (a, flag) => {
    if (flag & 0x800) { try { return utf8.decode(a); } catch(e) {} }
    try { return utf8.decode(a); } catch(e) { return cp866.decode(a); }
  };
  let p = 0, n = 0, shown = 0;
  while (p + 46 <= cdBuf.byteLength) {
    if (dv.getUint32(p, true) !== 0x02014b50) break;
    const flag = dv.getUint16(p + 8, true);
    const csize = dv.getUint32(p + 20, true);
    const usize = dv.getUint32(p + 24, true);
    const nlen = dv.getUint16(p + 28, true);
    const elen = dv.getUint16(p + 30, true);
    const clen = dv.getUint16(p + 32, true);
    const name = dec(u8.subarray(p + 46, p + 46 + nlen), flag);
    n++;
    if (!filt || name.toLowerCase().indexOf(filt.toLowerCase()) >= 0) {
      if (shown < 4000) { out.push(usize + "\t" + name); shown++; }
    }
    p += 46 + nlen + elen + clen;
  }
  out.push("ENTRIES_PARSED " + n + " SHOWN " + shown);
  return out.join("\n");
})()'''


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    url = sys.argv[1]
    filt = sys.argv[2] if len(sys.argv) > 2 else ""
    print(TEMPLATE % {"url": esc(url), "filt": esc(filt)})
    return 0


if __name__ == "__main__":
    sys.exit(main())
