/* generated by mk_textsearch.py: search '5.17' (ASCII-only, deferred postback) */
(() => {
  const tx = document.querySelector('input[id$="FileArchiveFilter_txtDescr"]');
  const btn = document.querySelector('input[id$="FileArchiveFilter_btnSearch"]');
  if (!tx || !btn) return "NO_CONTROLS";
  tx.value = "5.17";
  setTimeout(() => btn.click(), 300);
  return "SEARCH_SCHEDULED q=" + tx.value;
})()
