/* generated by mk_rect.py: rects of 'a,div[role="button"],span' (trusted-click coordinates) */
(() => {
  let els = Array.prototype.slice.call(document.querySelectorAll("a,div[role=\u0022button\u0022],span"));
  els = els.filter(e => (e.innerText || e.textContent || "").indexOf("\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b") >= 0);
  if (!els.length) return "NO_MATCH selector=a,div[role=\u0022button\u0022],span";
  if (0) { try { els[0].scrollIntoView({block: "center", behavior: "instant"}); } catch (e) { els[0].scrollIntoView(); } }
  const out = ["MATCHES " + els.length + " viewport=" + innerWidth + "x" + innerHeight];
  els.slice(0, 40).forEach((e, i) => {
    const r = e.getBoundingClientRect();
    const cx = Math.round(r.left + r.width / 2), cy = Math.round(r.top + r.height / 2);
    const vis = r.width > 0 && r.height > 0 && cy >= 0 && cy < innerHeight;
    const txt = (e.innerText || e.textContent || "").replace(/\s+/g, " ").slice(0, 60);
    out.push("#" + (i + 1) + " " + cx + "," + cy + " w=" + Math.round(r.width) +
             " h=" + Math.round(r.height) + " vis=" + vis + " tag=" + e.tagName +
             " href=" + (e.getAttribute("href") || "-") + " text=" + txt);
  });
  return out.join("\n");
})()
