/* generated by mk_textsearch.py: search 'прошив' (ASCII-only, deferred postback) */
(() => {
  const tx = document.querySelector('input[id$="FileArchiveFilter_txtDescr"]');
  const btn = document.querySelector('input[id$="FileArchiveFilter_btnSearch"]');
  if (!tx || !btn) return "NO_CONTROLS";
  tx.value = "\u043f\u0440\u043e\u0448\u0438\u0432";
  setTimeout(() => btn.click(), 300);
  return "SEARCH_SCHEDULED q=" + tx.value;
})()
