/* generated by mk_setselect.py: drdCategory -> 'Контрольно' (ASCII-only, deferred postback) */
(() => {
  const sel = document.querySelector('select[id$="drdCategory"]');
  if (!sel) return "NO_SELECT drdCategory";
  const want = "\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u043e";
  let hit = null;
  for (const o of sel.options) { const t = (o.text || "").trim(); if (t.indexOf(want) === 0) { hit = o; break; } }
  if (!hit) return "NO_OPTION " + Array.from(sel.options).map(o => o.text).join(" / ");
  sel.value = hit.value;
  const nm = sel.name;
  setTimeout(() => { try { __doPostBack(nm, ""); } catch (e) { sel.dispatchEvent(new Event("change", {bubbles:true})); } }, 300);
  return "SCHEDULED " + nm + " => " + hit.text;
})()
