/* generated by mk_setselect.py: drdBrand -> 'АТОЛ' (ASCII-only, deferred postback) */
(() => {
  const sel = document.querySelector('select[id$="drdBrand"]');
  if (!sel) return "NO_SELECT drdBrand";
  const want = "\u0410\u0422\u041e\u041b";
  let hit = null;
  for (const o of sel.options) { const t = (o.text || "").trim(); if (t.indexOf(want) === 0) { hit = o; break; } }
  if (!hit) return "NO_OPTION " + Array.from(sel.options).map(o => o.text).join(" / ");
  sel.value = hit.value;
  const nm = sel.name;
  setTimeout(() => { try { __doPostBack(nm, ""); } catch (e) { sel.dispatchEvent(new Event("change", {bubbles:true})); } }, 300);
  return "SCHEDULED " + nm + " => " + hit.text;
})()
